<?xml version="1.0"?>
<package format="2">
  <name>mak4_sim_cpp</name>
  <version>1.0.0</version>
  <description>MAK4 无人机仿真系统 (C++实现版)</description>
  <maintainer email="zcy@todo.todo">zcy</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>mavros_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>pcl_ros</depend>
  <depend>octomap_msgs</depend>

  <build_depend>yaml-cpp</build_depend>
  <exec_depend>yaml-cpp</exec_depend>

  <export></export>
</package>
